package com.starnetsecurity.parkClientServer.service;

import com.starnetsecurity.common.exception.BizException;

import java.util.List;
import java.util.Map;

/**
 * Created by 陈峰 on 2017/10/13.
 */
public interface ReportStatisticsService {
    public List<Map<String, Object>> getDepInfo(String carparkId) throws BizException;

    public List<Map<String, Object>> getAllChargesReport(Integer page,
                                                         Integer size,
                                                         String beginTime,
                                                         String endTime,
                                                         String chargeReceiveCarNo,
                                                         String depName,
                                                         String carparkName,
                                                         String chargeReceiveSubType,
                                                         Float chargeReceiveAmountMin,
                                                         Float chargeReceiveAmountMax,
                                                         String chargeDiscountInfo,
                                                         String chargeReceivePostName,
                                                         String memo,
                                                         String operatorName,
                                                         String chargeReceiveId,
                                                         String carparkId,
                                                         String depId,
                                                         String chargeReceivePost,
                                                         String chargeReceiveOperatorId,
                                                         String chargeReceiveCarpark) throws BizException;

    public Integer getAllChargesReportCount(Integer page,
                                            Integer size,
                                            String beginTime,
                                            String endTime,
                                            String chargeReceiveCarNo,
                                            String depName,
                                            String carparkName,
                                            String chargeReceiveSubType,
                                            Float chargeReceiveAmountMin,
                                            Float chargeReceiveAmountMax,
                                            String chargeDiscountInfo,
                                            String chargeReceivePostName,
                                            String memo,
                                            String operatorName,
                                            String chargeReceiveId,
                                            String carparkId,
                                            String depId,
                                            String chargeReceivePost,
                                            String chargeReceiveOperatorId,
                                            String chargeReceiveCarpark) throws BizException;

    public List<Map<String, Object>> getBoothChargesReport(Integer page,
                                                           Integer size,
                                                           String beginTime,
                                                           String endTime,
                                                           String depId,
                                                           String depName,
                                                           String carparkId,
                                                           String carparkName,
                                                           String boothId,
                                                           String boothName,
                                                           Integer chargeCountMin,
                                                           Integer chargeCountMax,
                                                           Float availSumAmountMin,
                                                           Float availSumAmountMax,
                                                           Float availMaxAmountMin,
                                                           Float availMaxAmountMax,
                                                           Float availMinAmountMin,
                                                           Float availMinAmountMax,
                                                           Float availAvgAmountMin,
                                                           Float availAvgAmountMax,
                                                           Float realSumAmountMin,
                                                           Float realSumAmountMax,
                                                           Float realMaxAmountMin,
                                                           Float realMaxAmountMax,
                                                           Float realMinAmountMin,
                                                           Float realMinAmountMax,
                                                           Float realAvgAmountMin,
                                                           Float realAvgAmountMax,
                                                           String reportType) throws BizException;

    public Integer getBoothChargesReportCount(Integer page,
                                              Integer size,
                                              String beginTime,
                                              String endTime,
                                              String depId,
                                              String depName,
                                              String carparkId,
                                              String carparkName,
                                              String boothId,
                                              String boothName,
                                              Integer chargeCountMin,
                                              Integer chargeCountMax,
                                              Float availSumAmountMin,
                                              Float availSumAmountMax,
                                              Float availMaxAmountMin,
                                              Float availMaxAmountMax,
                                              Float availMinAmountMin,
                                              Float availMinAmountMax,
                                              Float availAvgAmountMin,
                                              Float availAvgAmountMax,
                                              Float realSumAmountMin,
                                              Float realSumAmountMax,
                                              Float realMaxAmountMin,
                                              Float realMaxAmountMax,
                                              Float realMinAmountMin,
                                              Float realMinAmountMax,
                                              Float realAvgAmountMin,
                                              Float realAvgAmountMax,
                                              String reportType) throws BizException;

    public List<Map<String, Object>> getChargeTypeReport(Integer page,
                                                         Integer size,
                                                         String beginTime,
                                                         String endTime,
                                                         String depId,
                                                         String depName,
                                                         String carparkId,
                                                         String carparkName,
                                                         String chargeSubType,
                                                         Integer chargeCountMin,
                                                         Integer chargeCountMax,
                                                         Float availSumAmountMin,
                                                         Float availSumAmountMax,
                                                         Float availMaxAmountMin,
                                                         Float availMaxAmountMax,
                                                         Float availMinAmountMin,
                                                         Float availMinAmountMax,
                                                         Float availAvgAmountMin,
                                                         Float availAvgAmountMax,
                                                         Float realSumAmountMin,
                                                         Float realSumAmountMax,
                                                         Float realMaxAmountMin,
                                                         Float realMaxAmountMax,
                                                         Float realMinAmountMin,
                                                         Float realMinAmountMax,
                                                         Float realAvgAmountMin,
                                                         Float realAvgAmountMax,
                                                         String reportType) throws BizException;

    public Integer getChargeTypeReportCount(Integer page,
                                            Integer size,
                                            String beginTime,
                                            String endTime,
                                            String depId,
                                            String depName,
                                            String carparkId,
                                            String carparkName,
                                            String chargeSubType,
                                            Integer chargeCountMin,
                                            Integer chargeCountMax,
                                            Float availSumAmountMin,
                                            Float availSumAmountMax,
                                            Float availMaxAmountMin,
                                            Float availMaxAmountMax,
                                            Float availMinAmountMin,
                                            Float availMinAmountMax,
                                            Float availAvgAmountMin,
                                            Float availAvgAmountMax,
                                            Float realSumAmountMin,
                                            Float realSumAmountMax,
                                            Float realMaxAmountMin,
                                            Float realMaxAmountMax,
                                            Float realMinAmountMin,
                                            Float realMinAmountMax,
                                            Float realAvgAmountMin,
                                            Float realAvgAmountMax,
                                            String reportType) throws BizException;

    public List<Map<String, Object>> getAttributeChargeReport(Integer page,
                                                              Integer size,
                                                              String beginTime,
                                                              String endTime,
                                                              String depId,
                                                              String depName,
                                                              String carparkId,
                                                              String carparkName,
                                                              String carType,
                                                              Integer chargeCountMin,
                                                              Integer chargeCountMax,
                                                              Float availSumAmountMin,
                                                              Float availSumAmountMax,
                                                              Float availMaxAmountMin,
                                                              Float availMaxAmountMax,
                                                              Float availMinAmountMin,
                                                              Float availMinAmountMax,
                                                              Float availAvgAmountMin,
                                                              Float availAvgAmountMax,
                                                              Float realSumAmountMin,
                                                              Float realSumAmountMax,
                                                              Float realMaxAmountMin,
                                                              Float realMaxAmountMax,
                                                              Float realMinAmountMin,
                                                              Float realMinAmountMax,
                                                              Float realAvgAmountMin,
                                                              Float realAvgAmountMax,
                                                              String reportType) throws BizException;

    public Integer getAttributeChargeReportCount(Integer page,
                                                 Integer size,
                                                 String beginTime,
                                                 String endTime,
                                                 String depId,
                                                 String depName,
                                                 String carparkId,
                                                 String carparkName,
                                                 String carType,
                                                 Integer chargeCountMin,
                                                 Integer chargeCountMax,
                                                 Float availSumAmountMin,
                                                 Float availSumAmountMax,
                                                 Float availMaxAmountMin,
                                                 Float availMaxAmountMax,
                                                 Float availMinAmountMin,
                                                 Float availMinAmountMax,
                                                 Float availAvgAmountMin,
                                                 Float availAvgAmountMax,
                                                 Float realSumAmountMin,
                                                 Float realSumAmountMax,
                                                 Float realMaxAmountMin,
                                                 Float realMaxAmountMax,
                                                 Float realMinAmountMin,
                                                 Float realMinAmountMax,
                                                 Float realAvgAmountMin,
                                                 Float realAvgAmountMax,
                                                 String reportType) throws BizException;

    public List<Map<String, Object>> getAmountSectionReport(Integer page,
                                                            Integer size,
                                                            String beginTime,
                                                            String endTime,
                                                            String depId,
                                                            String depName,
                                                            String carparkId,
                                                            String carparkName,
                                                            String chargeAmountSection,
                                                            Integer chargeCountMin,
                                                            Integer chargeCountMax,
                                                            Float availSumAmountMin,
                                                            Float availSumAmountMax,
                                                            Float availMaxAmountMin,
                                                            Float availMaxAmountMax,
                                                            Float availMinAmountMin,
                                                            Float availMinAmountMax,
                                                            Float availAvgAmountMin,
                                                            Float availAvgAmountMax,
                                                            Float realSumAmountMin,
                                                            Float realSumAmountMax,
                                                            Float realMaxAmountMin,
                                                            Float realMaxAmountMax,
                                                            Float realMinAmountMin,
                                                            Float realMinAmountMax,
                                                            Float realAvgAmountMin,
                                                            Float realAvgAmountMax,
                                                            String reportType) throws BizException;
    public Integer getAmountSectionReportCount(Integer page,
                                               Integer size,
                                               String beginTime,
                                               String endTime,
                                               String depId,
                                               String depName,
                                               String carparkId,
                                               String carparkName,
                                               String chargeAmountSection,
                                               Integer chargeCountMin,
                                               Integer chargeCountMax,
                                               Float availSumAmountMin,
                                               Float availSumAmountMax,
                                               Float availMaxAmountMin,
                                               Float availMaxAmountMax,
                                               Float availMinAmountMin,
                                               Float availMinAmountMax,
                                               Float availAvgAmountMin,
                                               Float availAvgAmountMax,
                                               Float realSumAmountMin,
                                               Float realSumAmountMax,
                                               Float realMaxAmountMin,
                                               Float realMaxAmountMax,
                                               Float realMinAmountMin,
                                               Float realMinAmountMax,
                                               Float realAvgAmountMin,
                                               Float realAvgAmountMax,
                                               String reportType) throws BizException;

    public List<Map<String, Object>> getParkingSituationReport(Integer page,
                                                               Integer size,
                                                               String beginTime,
                                                               String endTime,
                                                               String depId,
                                                               String depName,
                                                               String carparkId,
                                                               String carparkName,
                                                               String parkingDurationSection,
                                                               Integer inCountMin,
                                                               Integer inCountMax,
                                                               Integer outCountMin,
                                                               Integer outCountMax,
                                                               Integer carCountMin,
                                                               Integer carCountMax,
                                                               Integer sumMinuteMin,
                                                               Integer sumMinuteMax,
                                                               Integer maxMinuteMin,
                                                               Integer maxMinuteMax,
                                                               Integer minMinuteMin,
                                                               Integer minMinuteMax,
                                                               Integer avgMinuteMin,
                                                               Integer avgMinuteMax,
                                                               String reportType,
                                                               /*0-不需要停车时长， 1-需要停车时长*/
                                                               String isExistDuration) throws BizException;

    public Integer getParkingSituationReportCount(Integer page,
                                                  Integer size,
                                                  String beginTime,
                                                  String endTime,
                                                  String depId,
                                                  String depName,
                                                  String carparkId,
                                                  String carparkName,
                                                  String parkingDurationSection,
                                                  Integer inCountMin,
                                                  Integer inCountMax,
                                                  Integer outCountMin,
                                                  Integer outCountMax,
                                                  Integer carCountMin,
                                                  Integer carCountMax,
                                                  Integer sumMinuteMin,
                                                  Integer sumMinuteMax,
                                                  Integer maxMinuteMin,
                                                  Integer maxMinuteMax,
                                                  Integer minMinuteMin,
                                                  Integer minMinuteMax,
                                                  Integer avgMinuteMin,
                                                  Integer avgMinuteMax,
                                                  String reportType,
                                                   /*0-不需要停车时长， 1-需要停车时长*/
                                                  String isExistDuration) throws BizException;

    public List<Map<String, Object>> getVehicleAttributeReport(Integer page,
                                                               Integer size,
                                                               String beginTime,
                                                               String endTime,
                                                               String depId,
                                                               String depName,
                                                               String carparkId,
                                                               String carparkName,
                                                               String carType,
                                                               Integer inCountMin,
                                                               Integer inCountMax,
                                                               Integer outCountMin,
                                                               Integer outCountMax,
                                                               Integer carCountMin,
                                                               Integer carCountMax,
                                                               Integer sumMinuteMin,
                                                               Integer sumMinuteMax,
                                                               Integer maxMinuteMin,
                                                               Integer maxMinuteMax,
                                                               Integer minMinuteMin,
                                                               Integer minMinuteMax,
                                                               Integer avgMinuteMin,
                                                               Integer avgMinuteMax,
                                                               String reportType) throws BizException;

    public Integer getVehicleAttributeReportCount(Integer page,
                                                  Integer size,
                                                  String beginTime,
                                                  String endTime,
                                                  String depId,
                                                  String depName,
                                                  String carparkId,
                                                  String carparkName,
                                                  String carType,
                                                  Integer inCountMin,
                                                  Integer inCountMax,
                                                  Integer outCountMin,
                                                  Integer outCountMax,
                                                  Integer carCountMin,
                                                  Integer carCountMax,
                                                  Integer sumMinuteMin,
                                                  Integer sumMinuteMax,
                                                  Integer maxMinuteMin,
                                                  Integer maxMinuteMax,
                                                  Integer minMinuteMin,
                                                  Integer minMinuteMax,
                                                  Integer avgMinuteMin,
                                                  Integer avgMinuteMax,
                                                  String reportType) throws BizException;

    public List<Map<String, Object>> getBoothVehicleFlowReport(Integer page,
                                                               Integer size,
                                                               String beginTime,
                                                               String endTime,
                                                               String depId,
                                                               String depName,
                                                               String carparkId,
                                                               String carparkName,
                                                               String boothId,
                                                               String boothName,
                                                               Integer inCountMin,
                                                               Integer inCountMax,
                                                               Integer outCountMin,
                                                               Integer outCountMax,
                                                               Integer carCountMin,
                                                               Integer carCountMax,
                                                               Integer sumMinuteMin,
                                                               Integer sumMinuteMax,
                                                               Integer maxMinuteMin,
                                                               Integer maxMinuteMax,
                                                               Integer minMinuteMin,
                                                               Integer minMinuteMax,
                                                               Integer avgMinuteMin,
                                                               Integer avgMinuteMax,
                                                               String reportType) throws BizException;
    public Integer getBoothVehicleFlowReportCount(Integer page,
                                                  Integer size,
                                                  String beginTime,
                                                  String endTime,
                                                  String depId,
                                                  String depName,
                                                  String carparkId,
                                                  String carparkName,
                                                  String boothId,
                                                  String boothName,
                                                  Integer inCountMin,
                                                  Integer inCountMax,
                                                  Integer outCountMin,
                                                  Integer outCountMax,
                                                  Integer carCountMin,
                                                  Integer carCountMax,
                                                  Integer sumMinuteMin,
                                                  Integer sumMinuteMax,
                                                  Integer maxMinuteMin,
                                                  Integer maxMinuteMax,
                                                  Integer minMinuteMin,
                                                  Integer minMinuteMax,
                                                  Integer avgMinuteMin,
                                                  Integer avgMinuteMax,
                                                  String reportType) throws BizException;

    public List<Map<String, Object>> getBoothList(String depId, String boothId) throws  BizException;

    public List<Map<String, Object>> getCarparkList(String depId, String carparkId, String ownCarparkNo) throws BizException;

    public List<Map<String, Object>> getChargeReceiveSubType(String depId, String carparkId) throws BizException;

    public List<Map<String, Object>> getChargeTypeInfo(String depId, String carparkId) throws BizException;

    List prePayment(Integer start, Integer length, String orderOrechargeCarno, String chargeMemberKindName, String orderPrechargeCarparkName, String startTime, String endTime, String excelStart, String excelEnd);

    Long countPrePayment(String orderOrechargeCarno, String chargeMemberKindName, String orderPrechargeCarparkName, String startTime, String endTime,String excelStart, String excelEnd);

    List prePaymentList(String orderOrechargeCarno, String chargeMemberKindName, String orderPrechargeCarparkName, String startTime, String endTime,String excelStart, String excelEnd);

    /**
     * @Author chenbinbin
     * @Description 获取交易流水表
     * @Date 17:30 2020/2/28
     * @Param [start, length, startTime, endTime, payType, payStatus, excelStart, excelEnd, markInfo, carparkName, carno]
     * @return java.util.List
     **/
    List tranSaction(Integer start, Integer length, String startTime, String endTime, String payType, String payStatus, String excelStart,
                     String excelEnd,String markInfo,String carparkName,String carno);

    Long countTranSaction(String startTime, String endTime, String payType, String payStatus, String excelStart, String excelEnd,String markInfo,
                          String carparkName,String carno);

    List tranSactionList(String startTime, String endTime, String payType, String payStatus, String excelStart, String excelEnd,String markInfo,
                         String carparkName,String carno);

    Map getTranSactionFee(String startTime, String endTime, String payType, String payStatus, String excelStart, String excelEnd,String markInfo,
                          String carparkName,String carno);

    Map getDeptId(String carparkId);

    List<Map<String, Object>> prePaymentType() throws BizException;
}
